CREATE DATABASE multiverse_travels;

\c multiverse_travels;
CREATE TABLE TRAVELS
(
   ID SERIAL PRIMARY KEY
);

CREATE TABLE DESTINATIONS
(
   ID SERIAL PRIMARY KEY,
   LOCATION_ID INT NOT NULL,
   TRAVEL_ID INT REFERENCES travels(id) ON DELETE CASCADE
);