CREATE DATABASE multiverse_travels;

\c multiverse_travels;
CREATE TABLE TRAVELS(
   ID INT PRIMARY KEY     NOT NULL
);

CREATE TABLE DESTINATIONS(
   ID INT PRIMARY KEY      NOT NULL,
   LOCATION_ID           CHAR(50) NOT NULL,
   TRAVEL_ID         INT      NOT NULL
);