default: &default
  host: localhost
  port: "5432"
  user: admin
  password: admin
  adapter: postgres

development:
  <<: *default
  db: database_name_development

test:
  <<: *default
  db: database_name_test

production:
  <<: *default
  db: database_name_production